feat(cnb-fxrates): validate input args values

diff --git a/cnb-fxrates b/cnb-fxrates
--- a/cnb-fxrates
+++ b/cnb-fxrates
@@ -31,12 +31,26 @@ Environment variables:
         Used primarily for testing.
 "
 url="${CNB_FXRATES_URL:-https://www.cnb.cz/en/financial-markets/foreign-exchange-market/central-bank-exchange-rate-fixing/central-bank-exchange-rate-fixing/daily.txt}"
+declare -a valid_currency_codes
+valid_currency_codes=(AUD BRL BGN CAD CNY HRK DKK EUR HKD HUF ISK XDR INR IDR \
+ILS JPY MYR MXN NZD NOK PHP PLN RON RUB SGD ZAR KRW SEK CHF THB TRY GBP USD)
 currency="${1}"
 my_date="${2:-$(date --iso-8601)}"  # If date is not provided, use current date.
 
 if [[ ${#} -eq 0 || ${#} -gt 2 ]]; then
     echo "Error: Invalid number of arguments. See usage." >&2
     echo "${help_msg}"
+    exit 1
+fi
+code_match=0
+for valid_code in "${valid_currency_codes[@]}"; do
+    if [[ "${currency}" == "${valid_code}" ]]; then
+        code_match=1
+        break
+    fi
+done
+if [[ ${code_match} -ne 1 ]]; then
+    echo "Error: Invalid currency code. Valid codes: ${valid_currency_codes[*]}" >&2
     exit 1
 fi
 
