feat(normname): operate on multiple files
Includes a major refactoring.

diff --git a/normname b/normname
--- a/normname
+++ b/normname
@@ -1,30 +1,57 @@
 #!/usr/bin/env bash
 #
-# Normalize (rename) filename according to the rules below:
-#   * Change uppercase to lowercase.
-#   * Replace whitespaceses with underscores.
-#   * Remove Czech diacritics.
+# Normalize file names.
 #
-# Args:
-#   $1: filename to normalize
+# For the set of modifications see the function `normalize`.
 #
 
 set -o errexit
 
 
-orig_path="${1}"
-orig_dir=$(dirname "${orig_path}")
-orig_name=$(basename "${orig_path}")
+# Return normalized version of ${1}.
+#
+# * Change uppercase to lowercase.
+# * Replace whitespaceses with underscores.
+# * Remove Czech diacritics.
+normalize() {
+    local DIACRITICS NO_DIACRITICS
+    readonly DIACRITICS='ěščřžýáíéĚŠČŘŽÝÁÍÉ'
+    readonly NO_DIACRITICS='escrzyaieESCRZYAIE'
+    echo "${1}" \
+        | tr '[:upper:]' '[:lower:]' \
+        | tr ' ' '_' \
+        | sed "y/${DIACRITICS}/${NO_DIACRITICS}/"
+}
 
-diacritics='ěščřžýáíéĚŠČŘŽÝÁÍÉ'
-no_diacritics='escrzyaieESCRZYAIE'
-new_name=$(\
-    echo "${orig_name}" \
-    | tr '[:upper:]' '[:lower:]' \
-    | tr ' ' '_' \
-    | sed "y/${diacritics}/${no_diacritics}/" \
-)
-new_path="${orig_dir}/${new_name}"
 
-echo "${orig_path} -> ${new_path}"
-mv "${orig_path}" "${new_path}"
+# Main entry point
+main() {
+    if [[ ${#} -eq 0 ]]; then
+        echo "error: missing files to operate on" >&2
+        echo
+        echo "usage:"
+        echo "  ${0} FILE... "
+        exit 1
+    fi
+
+    local orig_path orig_dir orig_name
+    for orig_path in "${@}"; do
+        orig_dir=$(dirname "${orig_path}")
+        orig_name=$(basename "${orig_path}")
+        new_name=$(normalize "${orig_name}")
+
+        if [[ "${new_name}" != "${orig_name}" ]]; then
+            local new_path
+            if [[ "${orig_dir}" == "." ]]; then
+                new_path="${new_name}"
+            else
+                new_path="${orig_dir}/${new_name}"
+            fi
+            mv "${orig_path}" "${new_path}"
+            echo "${orig_path} -> ${new_path}"
+        fi
+    done
+}
+
+
+main "${@}"
