fix(normname): don't overrride existing files
This may happen if there is an existing file which name is the same as
the name created by normalization. For example, there are 2 files:
'My File' and 'my_file'. So normalization of 'My File' could override
existing 'my_file'.

diff --git a/normname b/normname
--- a/normname
+++ b/normname
@@ -51,10 +51,17 @@ main() {
             else
                 new_path="${orig_dir}/${new_name}"
             fi
-            # TODO: consider adding --no-clobber flag to prevent overwriting an
-            # existing file
-            mv "${orig_path}" "${new_path}"
-            echo "${orig_path} -> ${new_path}"
+            local output
+            output=$(mv --verbose --no-clobber "${orig_path}" "${new_path}")
+            # Surprisingly, `--no-clobber' option doesn't change exit status if
+            # `new_path' already exists. It is silently skipped and in the
+            # `--verbose' mode there is no output.
+            if [[ ! "${output}" ]]; then
+                echo "error: normalization of '${orig_path}' would override existing file '${new_path}'" >&2
+                exit 2
+            else
+                echo "${orig_path} -> ${new_path}"
+            fi
         fi
     done
 }
